[build]
  command = "prisma generate && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  # This forces Prisma to generate a standard client, NOT a proxy client
  PRISMA_GENERATE_DATAPROXY = "false"
  PRISMA_SKIP_POSTINSTALL_GENERATE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]
  # Explicitly including the library engines for Linux (Netlify's OS)
  included_files = ["node_modules/.prisma/client/*.node", "prisma/schema.prisma"]
  timeout = 26
